server {
    listen 80;
    listen [::]:80;
    server_name api.aifit.living;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type "text/plain";
    }

    location / {
        return 404;
    }
}
